export const ADD_AVAILABLE_OPTION = "ADD_AVAILABLE_OPTION";
export const REMOVE_OPTION_FROM_AVAILABLE_OPTIONS =
  "REMOVE_OPTION_FROM_AVAILABLE_OPTIONS";
export const COMPUTE_ADDED_OPTION_PRICE = "COMPUTE_ADDED_OPTION_PRICE";
export const COMPUTE_TOTAL_PRICE = "COMPUTE_TOTAL_PRICE";
export const REMOVE_OPTION_FROM_CAR = "REMOVE_OPTION_FROM_CAR";
